# [Tarea 10] Ejercicios Unidad 04-C | Descomposición LU
### Realizado por : Correa Adrian
### Link de GitHub:https://github.com/afca2002/Tarea10.git
### fecha: 23/01/2025

Resuelva los ejercicios adjuntos.

# Ejercicio 1

Realice las siguientes **multiplicaciones matriz-matriz**:

 **a)**  
   
   \begin{pmatrix}
   2 & -3 \\
   3 & -1
   \end{pmatrix}
  
   \begin{pmatrix}
   1 & 5 \\
   2 & 0
   \end{pmatrix}
   

 **b)**  
   
   \begin{pmatrix}
   2 & -3 \\
   3 & -1
   \end{pmatrix}
   
   \begin{pmatrix}
   1 & 5 & -4 \\
   -3 & 2 & 0
   \end{pmatrix}
   
   **c)**  
   
   \begin{pmatrix}
   2 & -3 & 1 \\
   4 & 3 & 0 \\
   5 & 2 & -4
   \end{pmatrix}
  
   \begin{pmatrix}
   0 & 1 & -2 \\
   1 & 0 & -1 \\
   2 & 3 & -2
   \end{pmatrix}
   
 **d)**  
   
   \begin{pmatrix}
   2 & 1 & 2 \\
   -2 & 3 & 0 \\
   2 & -1 & 3
   \end{pmatrix}
   
   \begin{pmatrix}
   1 & -2 \\
   -4 & 1 \\
   0 & 2
   \end{pmatrix}
   


In [2]:
import numpy as np

#  a)
A_a = np.array([[2, -3],
                [3, -1]])
B_a = np.array([[1,  5],
                [2,  0]])
C_a = A_a @ B_a
print("a) A * B =\n", C_a, "\n")

#  b)
A_b = np.array([[2, -3],
                [3, -1]])
B_b = np.array([[ 1,  5, -4],
                [-3,  2,  0]])
C_b = A_b @ B_b
print("b) A * B =\n", C_b, "\n")

#  c)
A_c = np.array([[ 2, -3,  1],
                [ 4,  3,  0],
                [ 5,  2, -4]])
B_c = np.array([[ 0,  1, -2],
                [ 1,  0, -1],
                [ 2,  3, -2]])
C_c = A_c @ B_c
print("c) A * B =\n", C_c, "\n")

# d)
A_d = np.array([[ 2,  1,  2],
                [-2,  3,  0],
                [ 2, -1,  3]])
B_d = np.array([[ 1, -2],
                [-4,  1],
                [ 0,  2]])
C_d = A_d @ B_d
print("d) A * B =\n", C_d)


a) A * B =
 [[-4 10]
 [ 1 15]] 

b) A * B =
 [[ 11   4  -8]
 [  6  13 -12]] 

c) A * B =
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]] 

d) A * B =
 [[ -2   1]
 [-14   7]
 [  6   1]]


# Ejercicio 2

Determine cuáles de las siguientes matrices son **no singulares** y, en caso de serlo, **calcule la inversa** de esas matrices:

 **a)**  
   
   \begin{pmatrix}
   4 & 2 & 6 \\
   3 & 0 & 7 \\
   -2 & -1 & -3
   \end{pmatrix}
   

 **b)**  
   
   \begin{pmatrix}
   1 & 2 & 0 \\
   2 & 1 & -1 \\
   3 & 1 & 1
   \end{pmatrix}
   

 **c)**  
   
   \begin{pmatrix}
   1 & 1 & -1 & 1 \\
   1 & 2 & -4 & -2 \\
   2 & 1 & 1 & 5 \\
   -1 & 0 & -2 & -4
   \end{pmatrix}
   

 **d)**  
   
   \begin{pmatrix}
   4 & 0 & 0 & 0\\
   6 & 7 & 0 & 0\\
   9 & 11 & 1 & 0 \\
   5 & 4 & 1 & 1  
   \end{pmatrix}
   




In [4]:
import numpy as np

A = np.array([
    [ 4,  2,  6],
    [ 3,  0,  7],
    [-2, -1, -3]
])

B = np.array([
    [ 1,  2,  0],
    [ 2,  1, -1],
    [ 3,  1,  1]
])

C = np.array([
    [ 1,  1, -1,  1],
    [ 1,  2, -4, -2],
    [ 2,  1,  1,  5],
    [-1,  0, -2, -4]
])

D = np.array([
    [ 4,  0,  0,  0],
    [ 6,  7,  0,  0],
    [ 9, 11,  1,  0],
    [ 5,  4,  1,  1]
])

def check_invertibility_and_inverse(mat, name):
    rows, cols = mat.shape
    print(f"Matriz {name} de tamaño {rows}x{cols}")
    
    # Si no es cuadrada, no se puede invertir
    if rows != cols:
        print(f"→ La matriz {name} NO es cuadrada; no tiene inversa.\n")
        return
    
    # Para matrices cuadradas, hallamos el determinante
    det = np.linalg.det(mat)
    print(f"Determinante de {name} = {det:.4f}")
    
    # Verificamos si el determinante es distinto de cero
    if abs(det) < 1e-12:
        print(f"→ La matriz {name} es singular (det aproximadamente 0). No invertible.\n")
    else:
        inv_mat = np.linalg.inv(mat)
        print(f"→ La matriz {name} es no singular. Su inversa es:\n{inv_mat}\n")

# Chequeo para cada matriz
check_invertibility_and_inverse(A, "A")
check_invertibility_and_inverse(B, "B")
check_invertibility_and_inverse(C, "C")
check_invertibility_and_inverse(D, "D")


Matriz A de tamaño 3x3
Determinante de A = 0.0000
→ La matriz A es singular (det aproximadamente 0). No invertible.

Matriz B de tamaño 3x3
Determinante de B = -8.0000
→ La matriz B es no singular. Su inversa es:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

Matriz C de tamaño 4x4
Determinante de C = 0.0000
→ La matriz C es singular (det aproximadamente 0). No invertible.

Matriz D de tamaño 4x4
Determinante de D = 28.0000
→ La matriz D es no singular. Su inversa es:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]



# Ejercicio 3

Resuelva los siguientes **sistemas lineales 4×4** que comparten la misma matriz de coeficientes:

1. Sistema 1:


\begin{cases}
x_1 \;-\; x_2 \;+\; 2x_3 \;-\; x_4 \;=\; 6\\
x_1 \;-\;\;\;\; x_3 \;+\; x_4 \;=\; 4\\
2x_1 \;+\; x_2 \;+\; 3x_3 \;-\; 4x_4 \;=\; -2\\
\quad\quad -\; x_2 \;+\; x_3 \;-\; x_4 \;=\; 5
\end{cases}


2. Sistema 2:

\begin{cases}
x_1 \;-\; x_2 \;+\; 2x_3 \;-\; x_4 \;=\; 1\\
x_1 \;-\;\;\;\; x_3 \;+\; x_4 \;=\; 1\\
2x_1 \;+\; x_2 \;+\; 3x_3 \;-\; 4x_4 \;=\; 2\\
\quad\quad -\; x_2 \;+\; x_3 \;-\; x_4 \;=\; -1
\end{cases}



In [7]:
import numpy as np

# Matriz de coeficientes 
A = np.array([
    [ 1, -1,  2, -1],  
    [ 1,  0, -1,  1],  
    [ 2,  1,  3, -4],  
    [ 0, -1,  1, -1]   
])

# Términos independientes 
b1 = np.array([ 6,  4, -2,  5])  
b2 = np.array([ 1,  1,  2, -1])  

# Verificamos que A sea invertible
det_A = np.linalg.det(A)
print("Determinante de A:", det_A)
if abs(det_A) < 1e-12:
    print("La matriz de coeficientes es singular; no se puede invertir.")
    
else:
   
    x1 = np.linalg.solve(A, b1)
    x2 = np.linalg.solve(A, b2)
    
    # Mostramos las soluciones
    print("\nSolución del Sistema 1 (A x = b1):")
    print("x =", x1)
    
    print("\nSolución del Sistema 2 (A x = b2):")
    print("x =", x2)


Determinante de A: -7.999999999999998

Solución del Sistema 1 (A x = b1):
x = [ 3. -6. -2. -1.]

Solución del Sistema 2 (A x = b2):
x = [1. 1. 1. 1.]


# Ejercicio 4

Encuentre los valores de \(\alpha\) que hacen que la siguiente matriz sea **singular**:


A =
\begin{pmatrix}
1 & -1 & \alpha \\[6pt]
2 &  2 & 1      \\[6pt]
0 &  \alpha & -\tfrac{3}{2}
\end{pmatrix}


Para que \(A\) sea singular, su **determinante** debe ser **cero**. Es decir, necesitamos resolver:
\det(A) \;=\; 0.



In [9]:
import sympy

alpha = sympy.Symbol('alpha', real=True)

# Definimos la matriz A 
A = sympy.Matrix([
    [1,      -1,      alpha],
    [2,       2,          1],
    [0,   alpha,  -sympy.Rational(3,2)]
])

# Calculamos la determinante de A
detA = A.det()

# Resolvemos la ecuación det(A) = 0
soluciones = sympy.solve(sympy.Eq(detA, 0), alpha)

print("Matriz A:")
sympy.pprint(A)

print("\nDeterminante de A =")
sympy.pprint(detA)

print("\nValores de alpha que hacen det(A) = 0:")
sympy.pprint(soluciones)


Matriz A:
⎡1  -1   α  ⎤
⎢           ⎥
⎢2  2    1  ⎥
⎢           ⎥
⎣0  α   -3/2⎦

Determinante de A =
   2        
2⋅α  - α - 6

Valores de alpha que hacen det(A) = 0:
[-3/2, 2]


# Ejercicio 5

Resuelva los siguientes **sistemas lineales**:

a)



\begin{pmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
-1 & 0 & 1
\end{pmatrix}

\begin{pmatrix}
2 & 3 & -1\\
0 & -2 & 1\\
0 & 0 & 3
\end{pmatrix}

\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}
=
\begin{pmatrix} 2 \\ -1 \\ 1 \end{pmatrix}.


b)



\begin{pmatrix}
2 & 0 & 0\\
-1 & 1 & 0\\
3 & 2 & -1
\end{pmatrix}

\begin{pmatrix}
1 & 1 & 1\\
0 & 1 & 2\\
0 & 0 & 1
\end{pmatrix}

\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}
=
\begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix}.



In [1]:

import numpy as np

# a)

M1_a = np.array([
    [ 1,  0,  0],
    [ 2,  1,  0],
    [-1,  0,  1]
])
M2_a = np.array([
    [ 2,  3, -1],
    [ 0, -2,  1],
    [ 0,  0,  3]
])
# Producto de las dos matrices: matriz de coeficientes A
A_a = M1_a @ M2_a

# Vector de términos independientes
b_a = np.array([ 2, -1,  1])

# Resolvemos A_a x = b_a (verificamos si A_a es invertible)
det_A_a = np.linalg.det(A_a)
print("Sistema (a):\n")
print("Matriz de coeficientes A_a =\n", A_a)
print(f"Determinante(A_a) = {det_A_a:.4f}")

if abs(det_A_a) < 1e-12:
    print("La matriz A_a es singular. No se puede resolver por inversión directa.\n")
else:
    x_a = np.linalg.solve(A_a, b_a)
    print("Solución del sistema (a): x =", x_a, "\n")

# b) 

# Matrices que se multiplican para el sistema (b)
M1_b = np.array([
    [ 2,  0,  0],
    [-1,  1,  0],
    [ 3,  2, -1]
])
M2_b = np.array([
    [ 1,  1,  1],
    [ 0,  1,  2],
    [ 0,  0,  1]
])
# Producto de las dos matrices: matriz de coeficientes A
A_b = M1_b @ M2_b

# Vector de términos independientes
b_b = np.array([-1,  3,  0])

# Resolvemos A_b x = b_b
det_A_b = np.linalg.det(A_b)
print("Sistema (b):\n")
print("Matriz de coeficientes A_b =\n", A_b)
print(f"Determinante(A_b) = {det_A_b:.4f}")

if abs(det_A_b) < 1e-12:
    print("La matriz A_b es singular. No se puede resolver por inversión directa.\n")
else:
    x_b = np.linalg.solve(A_b, b_b)
    print("Solución del sistema (b): x =", x_b)


Sistema (a):

Matriz de coeficientes A_a =
 [[ 2  3 -1]
 [ 4  4 -1]
 [-2 -3  4]]
Determinante(A_a) = -12.0000
Solución del sistema (a): x = [-3.  3.  1.] 

Sistema (b):

Matriz de coeficientes A_b =
 [[ 2  2  2]
 [-1  0  1]
 [ 3  5  6]]
Determinante(A_b) = -2.0000
Solución del sistema (b): x = [ 0.5 -4.5  3.5]


# Ejercicio 6

Factorice las siguientes matrices en la descomposición LU  
mediante el algoritmo de factorización LU  
con 
$l_{ii} = 1$ para todas las $i$.


Se tienen las siguientes matrices:

**a)** 
   
   \begin{pmatrix}
   2 & -1 & 1 \\
   3 & 3 & 9 \\
   3 & 3 & 5
   \end{pmatrix}
   

**b)** 
   
   \begin{pmatrix}
   1.012 & -2.132 & 3.104 \\
   -2.132 & 4.096 & -7.013 \\
   3.104 & -7.013 & 0.014
   \end{pmatrix}
   

**c)**
    
   \begin{pmatrix}
   2 & 0 & 0 & 0 \\
   1 & 1.5 & 0 & 0 \\
   0 & -3 & 0.5 & 0 \\
   2 & -2 & 1 & 1
   \end{pmatrix}
   

**d)**
    
   \begin{pmatrix}
   2.1756 & 4.0231 & -2.1732 & 5.1967 \\
   -4.0231 & 6.0000 & 0 & 1.1973 \\
   -1.0000 & -5.2107 & 1.1111 & 0 \\
   6.0235 & 7.0000 & 0 & -4.1561
   \end{pmatrix}
   


In [12]:
import sympy

# Ajustes de impresión para Sympy
sympy.init_printing(use_unicode=True, wrap_line=False, no_global=True)

# (a)
A_a = sympy.Matrix([
    [2, -1,  1],
    [3,  3,  9],
    [3,  3,  5]
])
L_a, U_a, p_a = A_a.LUdecomposition()
print("Matriz (a):")
print("p_a =", p_a)
print("L_a =")
sympy.pprint(L_a)
print("U_a =")
sympy.pprint(U_a)
print("="*40, "\n")

# (b)
A_b = sympy.Matrix([
    [ 1.012, -2.132,  3.104],
    [-2.132,  4.096, -7.013],
    [ 3.104, -7.013,  0.014]
])
L_b, U_b, p_b = A_b.LUdecomposition()
print("Matriz (b):")
print("p_b =", p_b)
print("L_b =")
sympy.pprint(L_b)
print("U_b =")
sympy.pprint(U_b)
print("="*40, "\n")

# (c)
A_c = sympy.Matrix([
    [ 2,   0,   0,   0],
    [ 1, 1.5,   0,   0],
    [ 0,  -3, 0.5,   0],
    [ 2,  -2,   1,   1]
])
L_c, U_c, p_c = A_c.LUdecomposition()
print("Matriz (c):")
print("p_c =", p_c)
print("L_c =")
sympy.pprint(L_c)
print("U_c =")
sympy.pprint(U_c)
print("="*40, "\n")

# (d)
A_d = sympy.Matrix([
    [ 2.1756,  4.0231, -2.1732,  5.1967],
    [-4.0231,  6.0000,  0,       1.1973],
    [-1.0000, -5.2107,  1.1111,  0     ],
    [ 6.0235,  7.0000,  0,      -4.1561]
])
L_d, U_d, p_d = A_d.LUdecomposition()
print("Matriz (d):")
print("p_d =", p_d)
print("L_d =")
sympy.pprint(L_d)
print("U_d =")
sympy.pprint(U_d)


Matriz (a):
p_a = []
L_a =
⎡ 1   0  0⎤
⎢         ⎥
⎢3/2  1  0⎥
⎢         ⎥
⎣3/2  1  1⎦
U_a =
⎡2  -1    1  ⎤
⎢            ⎥
⎢0  9/2  15/2⎥
⎢            ⎥
⎣0   0    -4 ⎦

Matriz (b):
p_b = []
L_b =
⎡        1                 0          0⎤
⎢                                      ⎥
⎢-2.10671936758893         1          0⎥
⎢                                      ⎥
⎣3.06719367588933   1.19775552624215  1⎦
U_b =
⎡1.012        -2.132              3.104       ⎤
⎢                                             ⎥
⎢  0    -0.395525691699605  -0.473743083003951⎥
⎢                                             ⎥
⎣  0            0            -8.9391407742735 ⎦

Matriz (c):
p_c = []
L_c =
⎡ 1           0           0   0⎤
⎢                              ⎥
⎢1/2          1           0   0⎥
⎢                              ⎥
⎢ 0         -2.0          1   0⎥
⎢                              ⎥
⎣ 1   -1.33333333333333  2.0  1⎦
U_c =
⎡2   0    0   0⎤
⎢              ⎥
⎢0  1.5   0   0⎥
⎢              ⎥
⎢0   0   0.5  0⎥
⎢  

 ## Ejercicio 7

Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales:

### Sistemas Lineales

**a.**
\[
\begin{aligned}
2x_1 - x_2 + x_3 &= -1, \\
3x_1 + 3x_2 + 9x_3 &= 0, \\
3x_1 + 3x_2 + 5x_3 &= 4.
\end{aligned}
\]

**b.**
\[
\begin{aligned}
1.012x_1 - 2.132x_2 + 3.104x_3 &= 1.984, \\
-2.132x_1 + 4.096x_2 - 7.013x_3 &= -5.049, \\
3.104x_1 - 7.013x_2 + 0.014x_3 &= -3.895.
\end{aligned}
\]

**c.**
\[
\begin{aligned}
2x_1 &= 3, \\
x_1 + 1.5x_2 &= 4.5, \\
-3x_2 + 0.5x_3 &= -6.6, \\
2x_1 - 2x_2 + x_3 + x_4 &= 0.8.
\end{aligned}
\]

**d.**
\[
\begin{aligned}
2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 &= 17.102, \\
-4.0231x_1 + 6.0000x_2 + 1.1973x_4 &= -6.1593, \\
-1.0000x_1 - 5.2107x_2 + 1.1111x_3 &= 3.0004, \\
6.0235x_1 + 7.0000x_2 - 4.1561x_4 &= 0.0000.
\end{aligned}
\]


In [1]:
import numpy as np
from scipy.linalg import lu

# Función para resolver un sistema lineal utilizando descomposición LU
def solve_with_lu(A, b):
    # Realizamos la descomposición LU
    P, L, U = lu(A)
    
    # Resolver Ly = Pb
    Pb = np.dot(P, b)
    y = np.linalg.solve(L, Pb)
    
    # Resolver Ux = y
    x = np.linalg.solve(U, y)
    return x, P, L, U

# Sistemas Lineales

# Sistema a
A_a = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
], dtype=float)
b_a = np.array([-1, 0, 4], dtype=float)

# Sistema b
A_b = np.array([
    [1.012, -2.132, 3.104],
    [-2.132, 4.096, -7.013],
    [3.104, -7.013, 0.014]
], dtype=float)
b_b = np.array([1.984, -5.049, -3.895], dtype=float)

# Sistema c
A_c = np.array([
    [2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]
], dtype=float)
b_c = np.array([3, 4.5, -6.6, 0.8], dtype=float)

# Sistema d
A_d = np.array([
    [2.1756, 4.0231, -2.1732, 5.1967],
    [-4.0231, 6.0000, 0, 1.1973],
    [-1.0000, -5.2107, 1.1111, 0],
    [6.0235, 7.0000, 0, -4.1561]
], dtype=float)
b_d = np.array([17.102, -6.1593, 3.0004, 0], dtype=float)

# Resolviendo los sistemas
solutions = {}

# Sistema a
x_a, P_a, L_a, U_a = solve_with_lu(A_a, b_a)
solutions["a"] = x_a

# Sistema b
x_b, P_b, L_b, U_b = solve_with_lu(A_b, b_b)
solutions["b"] = x_b

# Sistema c
x_c, P_c, L_c, U_c = solve_with_lu(A_c, b_c)
solutions["c"] = x_c

# Sistema d
x_d, P_d, L_d, U_d = solve_with_lu(A_d, b_d)
solutions["d"] = x_d

# Mostrar resultados
for key, solution in solutions.items():
    print(f"Solución para el sistema {key}: {solution}")


Solución para el sistema a: [ 1.  2. -1.]
Solución para el sistema b: [1. 1. 1.]
Solución para el sistema c: [  1.5  -5.4 -30.8  21.5]
Solución para el sistema d: [ 4.5834584   0.64756529 22.5539797   7.01162597]
